
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:
   runs-on: ubuntu-latest
   timeout-minutes: 10

   steps:

    - name: Checkout
      uses: actions/checkout@v3
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Code coverage
    - name: code coverage
      run : dotnet test --collect:"XPlat Code Coverage"
      
  # upload artifacts
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./TestProject1/TestResults/**/coverage.cobertura.xml
    
   
