name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      delete_run_by_conclusion_pattern:
        description: 'Remove workflow by conclusion: action_required, cancelled, failure, success'
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - action_required
          - cancelled
          - failure
          - success
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        run: "${GITHUB_WORKSPACE}/.github/deletescript.sh"     
