name: Delete old workflow runs
on:
  schedule:
    - cron: '*/5 * * * *'
# 
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: awsdemo/delete-workflow-runs@v3
        with:
          token: ${{ github.token }}
          repository: ${{ github.awsdemo }}
          retain_days: 1
          keep_minimum_runs: 6
